version: '3.8'

services:
  aggregator:
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    container_name: aggregator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
<<<<<<< HEAD
      aggregator-network:
        ipv4_address: 172.28.0.4
=======
      - async-aggregator-network
>>>>>>> 2513ce1827810548cdfaa9cb57a7723663a0d770

  resource1:
    build:
      context: .
      dockerfile: resource/Dockerfile
    container_name: resource1
    environment:
      - RESOURCE_ID=resource-1
    dns:
      - 8.8.8.8
    networks:
<<<<<<< HEAD
      aggregator-network:
        ipv4_address: 172.28.0.5
=======
      - async-aggregator-network
>>>>>>> 2513ce1827810548cdfaa9cb57a7723663a0d770

  resource2:
    build:
      context: .
      dockerfile: resource/Dockerfile
    container_name: resource2
    environment:
      - RESOURCE_ID=resource-2
    dns:
      - 8.8.8.8
    networks:
<<<<<<< HEAD
      aggregator-network:
        ipv4_address: 172.28.0.3
=======
      - async-aggregator-network
>>>>>>> 2513ce1827810548cdfaa9cb57a7723663a0d770

  resource3:
    build:
      context: .
      dockerfile: resource/Dockerfile
    container_name: resource3
    environment:
      - RESOURCE_ID=resource-3
    dns:
      - 8.8.8.8
    networks:
<<<<<<< HEAD
      aggregator-network:
        ipv4_address: 172.28.0.2
=======
      - async-aggregator-network
>>>>>>> 2513ce1827810548cdfaa9cb57a7723663a0d770

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    ports:
      - "8082:8082"
    depends_on:
      - aggregator
    dns:
      - 8.8.8.8
    networks:
<<<<<<< HEAD
      aggregator-network:
        ipv4_address: 172.28.0.6
=======
      - async-aggregator-network

  maven-test:
    image: "maven:3.9.4-eclipse-temurin-17"
    container_name: maven-test
    working_dir: /workspace
    volumes:
      - ./:/workspace:rw
      - ~/.m2:/root/.m2:rw
    entrypoint: ["/bin/sh", "-c"]
    command: ["mvn -pl aggregator -am -Dtest=se.inera.asyncaggregator.aggregator.service.SseServiceTest test"]
    networks:
      - async-aggregator-network
>>>>>>> 2513ce1827810548cdfaa9cb57a7723663a0d770

networks:
  aggregator-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
